version: '3.8'

networks:
  k6:
  grafana:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:v2.33.5
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
      - grafana
      - prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.6
    networks:
      - grafana
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-config/dashboards:/var/lib/grafana/dashboards
      - ./grafana-config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: vadomen/k6-prometheus:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_REMOTE_URL=http://prometheus:9090/api/v1/write
      - K6_OUT=output-prometheus-remote
    volumes:
      - ./dist:/scripts
    depends_on:
      - prometheus
      - grafana

  k6-local:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./dist:/scripts
